name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    # we want to run ubuntu-latest but we'll pin to a specific version so CI is reproducable
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ '17' ] # Java is

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run all checks and tests
      run: ./gradlew compileTestJava check

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-java-${{ matrix.java }}
        path: build/test-results/test/
